### ISSUE TITLE
linter-sass-lint not working with linter 2.3.0

### ISSUE THREAD

**Issue by scottbert** [AtomLinter/linter-sass-lint#210]
---

- Atom version: 1.34.0
- linter version 2.3.0
- linter-sass-lint version: 1.8.3
- Global sass-lint version (if used):
- Platform:
  - [ x] OSX
  - [ ] Windows
  - [ ] Linux
- Expected behaviour: linting
- Actual behaviour / issue description: no linting

https://github.com/steelbrain/linter/issues/1606 - seems the legacy API has been removed from linter, which breaks a lot of linters including this one. Downgrading to linter 2.2.0 via apm works as a temporary fix

**Comment by Arcanemagus** [comment]
In the [v2.3.0 release](https://github.com/steelbrain/linter/releases/tag/v2.3.0) of `linter` support for the v1 API was removed, breaking semver. This means that this provider is no longer supported by the current version of `linter`.

To get this provider working again it will need to be upgrade to the v2 API, a guide for accomplishing that can be found here: [Upgrading to Standard Linter v2](https://github.com/steelbrain/linter/blob/v2.3.0/docs/guides/upgrading-to-standard-linter-v2.md).

Until this is fixed in order to use this provider you will need to downgrade to the last version of `linter` that supports the v1 API, you can do this with `apm install linter@2.2.0`.
