### ISSUE TITLE
Slow package activation

### ISSUE THREAD

**Issue by contra** [AtomLinter/linter-sass-lint#36]
![screen shot 2016-02-09 at 1 09 36 am](https://cloud.githubusercontent.com/assets/425716/12911820/e16efc74-cec9-11e5-9155-dfa9868b4549.png)

Consistently takes up to 1 second to initialize, causing the editor spin-up time to be sluggish.

**Comment by DanPurdy** [comment]
Thanks @contra I'm planning on giving everything a bit of an overhaul in the next few weeks with a view to improving all the little areas i've neglected. Activation speed will definitely be one of them, though most of it is linked to sass-lint itself.

**Comment by Arcanemagus** [comment]
@DanPurdy one major thing to consider here is that the time reported above is the initial activation time _while loading Atom and all other packages_. There is room for improvement for sure though.

Over in linter-php I had experimented with Atom's `activationHooks`, but there were several issues with the package never being activated in the first place! This has been fixed in v1.4.0, but the hacky method I was using to get the specs working with that doesn't seem to work any longer and I haven't had time to get them working again. This is definitely the way to go to prevent situations like this though, as your package would only load when conditions you specify are matched (Such as a `.sass` file being opened for the first time.).

I eventually want to get all the linters moved over to that model as Atom's startup time will be majorly improved (no linters loading all at once at the start!).

**Comment by DanPurdy** [comment]
Thanks, that would be ideal. I'll look into it again when i get some time soon. :smile:

**Comment by ypresto** [comment]
Also slow package loading time.

![image](https://cloud.githubusercontent.com/assets/400558/13723788/e639617e-e8b2-11e5-9696-22e1330cb8a6.png)
e

getPath() is very slow as it spawns child process.
So it should not be called on initialization.

https://github.com/AtomLinter/linter-sass-lint/blob/b6f7a8d44ae2a2734c0165a68c205ee619e1e776/lib/main.coffee#L7

**Comment by DanPurdy** [comment]
Looks to be resolved in #55 which was release with version v1.2.0 thanks to @ypresto will close for now.
