### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined at processNode

### ISSUE THREAD

**Issue by hellobrian** [AtomLinter/linter-sass-lint#9]
I'm using linter-sass-lint on Atom.
I have `linter@1.11.3` and `linter-sass-lint@0.6.2` in my atom packages.

I'm getting these errors every time I save.

Let me know if there's anymore information I can provide you to better resolve this issue. 
(Error message is truncated for brevity).

```
sass-lint had a problem 
Please consider filing an issue with sass-lint 
including the text below and any other information possible.

TypeError: Cannot read property 'start' of undefined 
at processNode 
(/Users/brianhan/.atom/packages/linter-sass-lint/node_modules/sass-lint/lib/rules/indentation.js:57:46) 

...
```

**Comment by Arcanemagus** [comment]
This looks to be an issue with `sass-lint` and not this package, does it work for you on that file from the command line?

**Comment by hellobrian** [comment]
No, it doesn't work in command line or gulp plugin either -- errors are consistent: 

```
TypeError: Cannot read property 'start' of undefined
```

I'll file an issue on the sass-lint repo if one isn't open already.

**Comment by hellobrian** [comment]
FYI for anyone who needs further direction on this same bug, please refer to https://github.com/sasstools/sass-lint/issues/389. 

sass-lint will error out because of the `indentation` rule when there's a mix of tabs and spaces in your scss file. 

I fixed my error by converting my tabs to spaces using an atom plugin called [whitespace](https://github.com/atom/whitespace)

**Comment by Arcanemagus** [comment]
I use that almost every day running through old code, thanks for linking out to the issue you filed!

**Comment by DanPurdy** [comment]
Yeah sorry, the AST we are currently using on `sass-lint` has patchy support for tabs at the moment, it's fixed in the latest upstream version but there's been some nasty regressions that we're hoping to see resolved soon and then we'll be able to upgrade. The indentation rule is then due for an overhaul as it's a little flaky at the moment and doesn't handle different line endings correctly.

Thanks thought @hellobrian, glad you managed to sort your issue.

For anyone else reading this issue if you see the warning `sass-lint` has had a problem it's almost 100% a `sass-lint` issue and not this plugin, please have a quick search over [here](https://github.com/sasstools/sass-lint/issues) or post a new issue with all the information that you got from the error message. Thanks!
